export const data = [
  {
    id: 1,
    quantity: 5,
    name: "i phone 13 pro case",
    description:
      "This stylish silicone case is super sturdy and shock absorbing. This case is especially for the latest models and therefore has a seamless fit. The case is made of the highest quality TPU silicone. The soft TPU material ensures that your phone is optimally protected against scratches, dirt and bumps. The cover is provided with all the necessary cutouts so that all ports and buttons remain accessible.",
    characterstics: [
      "Durable and long lasting",
      "TPU + Polycarbonate crystal transparent",
      "Precise cutouts",
      "Modern design",
      "Camera protection",
    ],
    selectQuantity: [1, 2, 3, 4, 5],
    color: "Transparent",
    price: 21.95,
    fits: ["Iphone 13 pro", "Iphone 14 pro"],
    img1: "https://imgs.search.brave.com/3cTFM_211W3aLQvCGzGZsyNhWgXZZCbW0mt-boeYmjo/rs:fit:570:570:1/g:ce/aHR0cHM6Ly9pLnBp/bmltZy5jb20vNzM2/eC80ZS8wNC82OC80/ZTA0Njg3MzZkM2Fl/OTkyYzYzYzJjYjk0/NWMzNDQxZi0taXBo/b25lLXMtcGhvbmUt/Y2FzZXMuanBn",
    img2: "https://m.media-amazon.com/images/I/71xPzaAz6XL._SY450_.jpg",
    img3: "https://m.media-amazon.com/images/I/71K8zibaf4L._SY450_.jpg",
  },
  {
    id: 2,
    quantity: 5,
    name: "i phone 13 pro case",
    description:
      "This stylish silicone case is super sturdy and shock absorbing. This case is especially for the latest models and therefore has a seamless fit. The case is made of the highest quality TPU silicone. The soft TPU material ensures that your phone is optimally protected against scratches, dirt and bumps. The cover is provided with all the necessary cutouts so that all ports and buttons remain accessible.",

    characterstics: [
      "Durable and long lasting",
      "TPU + Polycarbonate crystal transparent",
      "Precise cutouts",
      "Modern design",
      "Camera protection",
    ],
    selectQuantity: [1, 2, 3, 4, 5],
    color: "Transparent",
    price: 21.95,
    fits: ["Iphone 13 pro", "Iphone 14 pro"],
    img1: "https://imgs.search.brave.com/3cTFM_211W3aLQvCGzGZsyNhWgXZZCbW0mt-boeYmjo/rs:fit:570:570:1/g:ce/aHR0cHM6Ly9pLnBp/bmltZy5jb20vNzM2/eC80ZS8wNC82OC80/ZTA0Njg3MzZkM2Fl/OTkyYzYzYzJjYjk0/NWMzNDQxZi0taXBo/b25lLXMtcGhvbmUt/Y2FzZXMuanBn",
    img2: "https://m.media-amazon.com/images/I/71xPzaAz6XL._SY450_.jpg",
    img3: "https://m.media-amazon.com/images/I/71K8zibaf4L._SY450_.jpg",
  },
  {
    id: 3,
    quantity: 5,
    name: "i phone 13 pro case",
    description:
      "This stylish silicone case is super sturdy and shock absorbing. This case is especially for the latest models and therefore has a seamless fit. The case is made of the highest quality TPU silicone. The soft TPU material ensures that your phone is optimally protected against scratches, dirt and bumps. The cover is provided with all the necessary cutouts so that all ports and buttons remain accessible.",

    characterstics: [
      "Durable and long lasting",
      "TPU + Polycarbonate crystal transparent",
      "Precise cutouts",
      "Modern design",
      "Camera protection",
    ],
    selectQuantity: [1, 2, 3, 4, 5],
    color: "Transparent",
    price: 21.95,
    fits: ["Iphone 13 pro", "Iphone 14 pro"],
    img1: "https://imgs.search.brave.com/3cTFM_211W3aLQvCGzGZsyNhWgXZZCbW0mt-boeYmjo/rs:fit:570:570:1/g:ce/aHR0cHM6Ly9pLnBp/bmltZy5jb20vNzM2/eC80ZS8wNC82OC80/ZTA0Njg3MzZkM2Fl/OTkyYzYzYzJjYjk0/NWMzNDQxZi0taXBo/b25lLXMtcGhvbmUt/Y2FzZXMuanBn",
    img2: "https://m.media-amazon.com/images/I/71xPzaAz6XL._SY450_.jpg",
    img3: "https://m.media-amazon.com/images/I/71K8zibaf4L._SY450_.jpg",
  },
  {
    id: 4,
    quantity: 5,
    name: "i phone 13 pro case",
    description:
      "This stylish silicone case is super sturdy and shock absorbing. This case is especially for the latest models and therefore has a seamless fit. The case is made of the highest quality TPU silicone. The soft TPU material ensures that your phone is optimally protected against scratches, dirt and bumps. The cover is provided with all the necessary cutouts so that all ports and buttons remain accessible.",

    characterstics: [
      "Durable and long lasting",
      "TPU + Polycarbonate crystal transparent",
      "Precise cutouts",
      "Modern design",
      "Camera protection",
    ],
    selectQuantity: [1, 2, 3, 4, 5],
    color: "Transparent",
    price: 21.95,
    fits: ["Iphone 13 pro", "Iphone 14 pro"],
    img1: "https://imgs.search.brave.com/3cTFM_211W3aLQvCGzGZsyNhWgXZZCbW0mt-boeYmjo/rs:fit:570:570:1/g:ce/aHR0cHM6Ly9pLnBp/bmltZy5jb20vNzM2/eC80ZS8wNC82OC80/ZTA0Njg3MzZkM2Fl/OTkyYzYzYzJjYjk0/NWMzNDQxZi0taXBo/b25lLXMtcGhvbmUt/Y2FzZXMuanBn",
    img2: "https://m.media-amazon.com/images/I/71xPzaAz6XL._SY450_.jpg",
    img3: "https://m.media-amazon.com/images/I/71K8zibaf4L._SY450_.jpg",
  },
  {
    id: 5,
    name: "i phone 13 pro case",
    quantity: 5,
    description:
      "This stylish silicone case is super sturdy and shock absorbing. This case is especially for the latest models and therefore has a seamless fit. The case is made of the highest quality TPU silicone. The soft TPU material ensures that your phone is optimally protected against scratches, dirt and bumps. The cover is provided with all the necessary cutouts so that all ports and buttons remain accessible.",

    characterstics: [
      "Durable and long lasting",
      "TPU + Polycarbonate crystal transparent",
      "Precise cutouts",
      "Modern design",
      "Camera protection",
    ],
    selectQuantity: [1, 2, 3, 4, 5],
    color: "Transparent",
    price: 21.95,
    fits: ["Iphone 13 pro", "Iphone 14 pro"],
    img1: "https://imgs.search.brave.com/3cTFM_211W3aLQvCGzGZsyNhWgXZZCbW0mt-boeYmjo/rs:fit:570:570:1/g:ce/aHR0cHM6Ly9pLnBp/bmltZy5jb20vNzM2/eC80ZS8wNC82OC80/ZTA0Njg3MzZkM2Fl/OTkyYzYzYzJjYjk0/NWMzNDQxZi0taXBo/b25lLXMtcGhvbmUt/Y2FzZXMuanBn",
    img2: "https://m.media-amazon.com/images/I/71xPzaAz6XL._SY450_.jpg",
    img3: "https://m.media-amazon.com/images/I/71K8zibaf4L._SY450_.jpg",
  },
  {
    id: 6,
    quantity: 5,
    name: "i phone 13 pro case",
    description:
      "This stylish silicone case is super sturdy and shock absorbing. This case is especially for the latest models and therefore has a seamless fit. The case is made of the highest quality TPU silicone. The soft TPU material ensures that your phone is optimally protected against scratches, dirt and bumps. The cover is provided with all the necessary cutouts so that all ports and buttons remain accessible.",

    characterstics: [
      "Durable and long lasting",
      "TPU + Polycarbonate crystal transparent",
      "Precise cutouts",
      "Modern design",
      "Camera protection",
    ],
    selectQuantity: [1, 2, 3, 4, 5],
    color: "Transparent",
    price: 21.95,
    fits: ["Iphone 13 pro", "Iphone 14 pro"],
    img1: "https://imgs.search.brave.com/3cTFM_211W3aLQvCGzGZsyNhWgXZZCbW0mt-boeYmjo/rs:fit:570:570:1/g:ce/aHR0cHM6Ly9pLnBp/bmltZy5jb20vNzM2/eC80ZS8wNC82OC80/ZTA0Njg3MzZkM2Fl/OTkyYzYzYzJjYjk0/NWMzNDQxZi0taXBo/b25lLXMtcGhvbmUt/Y2FzZXMuanBn",
    img2: "https://m.media-amazon.com/images/I/71xPzaAz6XL._SY450_.jpg",
    img3: "https://m.media-amazon.com/images/I/71K8zibaf4L._SY450_.jpg",
  },
  {
    id: 7,
    quantity: 5,
    name: "i phone 13 pro case",
    description:
      "This stylish silicone case is super sturdy and shock absorbing. This case is especially for the latest models and therefore has a seamless fit. The case is made of the highest quality TPU silicone. The soft TPU material ensures that your phone is optimally protected against scratches, dirt and bumps. The cover is provided with all the necessary cutouts so that all ports and buttons remain accessible.",

    characterstics: [
      "Durable and long lasting",
      "TPU + Polycarbonate crystal transparent",
      "Precise cutouts",
      "Modern design",
      "Camera protection",
    ],
    selectQuantity: [1, 2, 3, 4, 5],
    color: "Transparent",
    price: 21.95,
    fits: ["Iphone 13 pro", "Iphone 14 pro"],
    img1: "https://imgs.search.brave.com/3cTFM_211W3aLQvCGzGZsyNhWgXZZCbW0mt-boeYmjo/rs:fit:570:570:1/g:ce/aHR0cHM6Ly9pLnBp/bmltZy5jb20vNzM2/eC80ZS8wNC82OC80/ZTA0Njg3MzZkM2Fl/OTkyYzYzYzJjYjk0/NWMzNDQxZi0taXBo/b25lLXMtcGhvbmUt/Y2FzZXMuanBn",
    img2: "https://m.media-amazon.com/images/I/71xPzaAz6XL._SY450_.jpg",
    img3: "https://m.media-amazon.com/images/I/71K8zibaf4L._SY450_.jpg",
  },
  {
    id: 8,
    quantity: 5,
    name: "i phone 13 pro case",
    description:
      "This stylish silicone case is super sturdy and shock absorbing. This case is especially for the latest models and therefore has a seamless fit. The case is made of the highest quality TPU silicone. The soft TPU material ensures that your phone is optimally protected against scratches, dirt and bumps. The cover is provided with all the necessary cutouts so that all ports and buttons remain accessible.",

    characterstics: [
      "Durable and long lasting",
      "TPU + Polycarbonate crystal transparent",
      "Precise cutouts",
      "Modern design",
      "Camera protection",
    ],
    selectQuantity: [1, 2, 3, 4, 5],
    color: "Transparent",
    price: 21.95,
    fits: ["Iphone 13 pro", "Iphone 14 pro"],
    img1: "https://imgs.search.brave.com/3cTFM_211W3aLQvCGzGZsyNhWgXZZCbW0mt-boeYmjo/rs:fit:570:570:1/g:ce/aHR0cHM6Ly9pLnBp/bmltZy5jb20vNzM2/eC80ZS8wNC82OC80/ZTA0Njg3MzZkM2Fl/OTkyYzYzYzJjYjk0/NWMzNDQxZi0taXBo/b25lLXMtcGhvbmUt/Y2FzZXMuanBn",
    img2: "https://m.media-amazon.com/images/I/71xPzaAz6XL._SY450_.jpg",
    img3: "https://m.media-amazon.com/images/I/71K8zibaf4L._SY450_.jpg",
  },
  {
    id: 9,
    quantity: 5,
    name: "i phone 13 pro case",
    description:
      "This stylish silicone case is super sturdy and shock absorbing. This case is especially for the latest models and therefore has a seamless fit. The case is made of the highest quality TPU silicone. The soft TPU material ensures that your phone is optimally protected against scratches, dirt and bumps. The cover is provided with all the necessary cutouts so that all ports and buttons remain accessible.",

    characterstics: [
      "Durable and long lasting",
      "TPU + Polycarbonate crystal transparent",
      "Precise cutouts",
      "Modern design",
      "Camera protection",
    ],
    selectQuantity: [1, 2, 3, 4, 5],
    color: "Transparent",
    price: 21.95,
    fits: ["Iphone 13 pro", "Iphone 14 pro"],
    img1: "https://imgs.search.brave.com/3cTFM_211W3aLQvCGzGZsyNhWgXZZCbW0mt-boeYmjo/rs:fit:570:570:1/g:ce/aHR0cHM6Ly9pLnBp/bmltZy5jb20vNzM2/eC80ZS8wNC82OC80/ZTA0Njg3MzZkM2Fl/OTkyYzYzYzJjYjk0/NWMzNDQxZi0taXBo/b25lLXMtcGhvbmUt/Y2FzZXMuanBn",
    img2: "https://m.media-amazon.com/images/I/71xPzaAz6XL._SY450_.jpg",
    img3: "https://m.media-amazon.com/images/I/71K8zibaf4L._SY450_.jpg",
  },
  {
    id: 10,
    name: "i phone 13 pro case",
    description:
      "This stylish silicone case is super sturdy and shock absorbing. This case is especially for the latest models and therefore has a seamless fit. The case is made of the highest quality TPU silicone. The soft TPU material ensures that your phone is optimally protected against scratches, dirt and bumps. The cover is provided with all the necessary cutouts so that all ports and buttons remain accessible.",

    characterstics: [
      "Durable and long lasting",
      "TPU + Polycarbonate crystal transparent",
      "Precise cutouts",
      "Modern design",
      "Camera protection",
    ],
    selectQuantity: [1, 2, 3, 4, 5],
    color: "Transparent",
    price: 21.95,
    fits: ["Iphone 13 pro", "Iphone 14 pro"],
    img1: "https://imgs.search.brave.com/3cTFM_211W3aLQvCGzGZsyNhWgXZZCbW0mt-boeYmjo/rs:fit:570:570:1/g:ce/aHR0cHM6Ly9pLnBp/bmltZy5jb20vNzM2/eC80ZS8wNC82OC80/ZTA0Njg3MzZkM2Fl/OTkyYzYzYzJjYjk0/NWMzNDQxZi0taXBo/b25lLXMtcGhvbmUt/Y2FzZXMuanBn",
    img2: "https://m.media-amazon.com/images/I/71xPzaAz6XL._SY450_.jpg",
    img3: "https://m.media-amazon.com/images/I/71K8zibaf4L._SY450_.jpg",
  },
  {
    id: 11,
    name: "i phone 13 pro case",
    description:
      "This stylish silicone case is super sturdy and shock absorbing. This case is especially for the latest models and therefore has a seamless fit. The case is made of the highest quality TPU silicone. The soft TPU material ensures that your phone is optimally protected against scratches, dirt and bumps. The cover is provided with all the necessary cutouts so that all ports and buttons remain accessible.",

    characterstics: [
      "Durable and long lasting",
      "TPU + Polycarbonate crystal transparent",
      "Precise cutouts",
      "Modern design",
      "Camera protection",
    ],
    selectQuantity: [1, 2, 3, 4, 5],
    color: "Transparent",
    price: 21.95,
    fits: ["Iphone 13 pro", "Iphone 14 pro"],
    img1: "https://imgs.search.brave.com/3cTFM_211W3aLQvCGzGZsyNhWgXZZCbW0mt-boeYmjo/rs:fit:570:570:1/g:ce/aHR0cHM6Ly9pLnBp/bmltZy5jb20vNzM2/eC80ZS8wNC82OC80/ZTA0Njg3MzZkM2Fl/OTkyYzYzYzJjYjk0/NWMzNDQxZi0taXBo/b25lLXMtcGhvbmUt/Y2FzZXMuanBn",
    img2: "https://m.media-amazon.com/images/I/71xPzaAz6XL._SY450_.jpg",
    img3: "https://m.media-amazon.com/images/I/71K8zibaf4L._SY450_.jpg",
  },
  {
    id: 12,
    name: "i phone 13 pro case",
    description:
      "This stylish silicone case is super sturdy and shock absorbing. This case is especially for the latest models and therefore has a seamless fit. The case is made of the highest quality TPU silicone. The soft TPU material ensures that your phone is optimally protected against scratches, dirt and bumps. The cover is provided with all the necessary cutouts so that all ports and buttons remain accessible.",

    characterstics: [
      "Durable and long lasting",
      "TPU + Polycarbonate crystal transparent",
      "Precise cutouts",
      "Modern design",
      "Camera protection",
    ],
    selectQuantity: [1, 2, 3, 4, 5],
    color: "Transparent",
    price: 21.95,
    fits: ["Iphone 13 pro", "Iphone 14 pro"],
    img1: "https://imgs.search.brave.com/3cTFM_211W3aLQvCGzGZsyNhWgXZZCbW0mt-boeYmjo/rs:fit:570:570:1/g:ce/aHR0cHM6Ly9pLnBp/bmltZy5jb20vNzM2/eC80ZS8wNC82OC80/ZTA0Njg3MzZkM2Fl/OTkyYzYzYzJjYjk0/NWMzNDQxZi0taXBo/b25lLXMtcGhvbmUt/Y2FzZXMuanBn",
    img2: "https://m.media-amazon.com/images/I/71xPzaAz6XL._SY450_.jpg",
    img3: "https://m.media-amazon.com/images/I/71K8zibaf4L._SY450_.jpg",
  },
];
